name: undercover

services:
  client:
    build:
      context: ./client
    environment:
      - API_URL=${API_URL:-http://localhost:3001}

  server:
    build:
      context: ./server

  word-gen:
    build:
      context: ./services
    environment:
      - FLASK_ENV=production